# Generated by Django 4.2 on 2023-12-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlunoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=25, verbose_name="Nome")),
                ("turma", models.CharField(max_length=20, verbose_name="Turma")),
                (
                    "responsavel",
                    models.CharField(
                        default="s/dados", max_length=25, verbose_name="Responsavel"
                    ),
                ),
                (
                    "telefone_responsavel",
                    models.CharField(
                        default="s/dados",
                        max_length=25,
                        verbose_name="Contato do responsável",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaProdutoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=25, verbose_name="Categoria"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FuncionarioModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funcionario",
                    models.CharField(max_length=25, verbose_name="Funcionário"),
                ),
                ("telefone", models.CharField(max_length=25, verbose_name="Telefone")),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoDebitoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aluno", models.CharField(max_length=25, verbose_name="aluno")),
                ("produto", models.CharField(max_length=25, verbose_name="produto")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="Valor"
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstoqueModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto", models.CharField(max_length=25, verbose_name="Produto")),
                ("codigo", models.CharField(max_length=25, verbose_name="Código")),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=5,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "preco_custo",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=5,
                        verbose_name="Preço custo",
                    ),
                ),
                (
                    "total_custo",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=5,
                        verbose_name="Total custo",
                    ),
                ),
                (
                    "preco_varejo",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=5,
                        verbose_name="Preço varejo",
                    ),
                ),
                (
                    "total_varejo",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=5,
                        verbose_name="Total varejo",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.categoriaprodutomodel",
                        verbose_name="Categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DebitoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="Valor"
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "codigo",
                    models.CharField(default=0, max_length=25, verbose_name="Código"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.alunomodel",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.estoquemodel",
                        verbose_name="Produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CadastrosVendaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Quantidade"
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor_unitário"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "produto",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.estoquemodel",
                        verbose_name="Produto",
                    ),
                ),
            ],
        ),
    ]
