# Generated by Django 4.2 on 2024-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlunoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Usuáiro"
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Unidade"
                    ),
                ),
                ("nome", models.CharField(max_length=25, verbose_name="Nome")),
                ("turma", models.CharField(max_length=20, verbose_name="Turma")),
                (
                    "responsavel",
                    models.CharField(max_length=25, verbose_name="Responsavel"),
                ),
                (
                    "telefone_responsavel",
                    models.CharField(
                        max_length=25, verbose_name="Contato do responsável"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CadastrosVendaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Usuário"
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Unidade"
                    ),
                ),
                (
                    "produto",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Produto"
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=0, max_digits=20, verbose_name="Quantidade"
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Valor_unitário"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Valor"
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaProdutoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Usuário"
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Unidade"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=25, verbose_name="Categoria"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DebitoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Usuário"
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Unidade"
                    ),
                ),
                (
                    "aluno",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Aluno"
                    ),
                ),
                (
                    "produto",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="produto"
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor unitário"
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Quantidade"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstoqueModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Usuário"
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Unidade"
                    ),
                ),
                (
                    "produto",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Produto"
                    ),
                ),
                ("codigo", models.CharField(max_length=25, verbose_name="Código")),
                ("quantidade", models.IntegerField(verbose_name="Quantidade")),
                (
                    "preco_custo",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Preço custo"
                    ),
                ),
                (
                    "total_custo",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Total custo"
                    ),
                ),
                (
                    "preco_varejo",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Preço varejo"
                    ),
                ),
                (
                    "total_varejo",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Total varejo"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        max_length=25, null=True, verbose_name="Categoria"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FuncionarioModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Usuáiro"
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Unidade"
                    ),
                ),
                (
                    "funcionario",
                    models.CharField(max_length=25, verbose_name="Funcionário"),
                ),
                ("telefone", models.CharField(max_length=25, verbose_name="Telefone")),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoDebitoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Usuáiro"
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Unidade"
                    ),
                ),
                ("aluno", models.CharField(max_length=25, verbose_name="Aluno")),
                ("produto", models.CharField(max_length=25, verbose_name="Produto")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="Valor"
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
            ],
        ),
        migrations.CreateModel(
            name="ModelAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=25, verbose_name="Usuáiro")),
                ("unidade", models.CharField(max_length=25, verbose_name="Unidade")),
                ("nome", models.CharField(max_length=25, verbose_name="Nome")),
                ("turma", models.CharField(max_length=20, verbose_name="Turma")),
                (
                    "responsavel",
                    models.CharField(max_length=25, verbose_name="Responsavel"),
                ),
                (
                    "tel_responsavel",
                    models.CharField(
                        max_length=25, verbose_name="Contato do responsável"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=25, verbose_name="Ususario")),
                ("unidade", models.CharField(max_length=25, verbose_name="Unidade")),
            ],
        ),
        migrations.CreateModel(
            name="UsuariosModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=25, verbose_name="Username")),
                ("password", models.CharField(max_length=25, verbose_name="Password")),
            ],
        ),
    ]
