# Generated by Django 4.2 on 2023-12-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0003_alter_cadastrosvendamodel_produto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaprodutomodel",
            name="categoria",
            field=models.CharField(max_length=25, verbose_name="Categoria"),
        ),
    ]
