# Generated by Django 4.2 on 2023-12-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0004_alter_categoriaprodutomodel_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoquemodel",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Quantidade"
            ),
        ),
    ]
