# Generated by Django 4.2 on 2023-12-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0006_alter_estoquemodel_preco_custo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alunomodel",
            name="responsavel",
            field=models.CharField(max_length=25, verbose_name="Responsavel"),
        ),
    ]
