# Generated by Django 4.2 on 2023-12-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0009_alter_cadastrosvendamodel_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrosvendamodel",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.estoquemodel",
                verbose_name="Produto",
            ),
        ),
    ]
