# Generated by Django 4.2 on 2023-12-26 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0012_alter_cadastrosvendamodel_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debitomodel",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.estoquemodel",
                verbose_name="Produto",
            ),
        ),
    ]
