# Generated by Django 4.2 on 2023-12-26 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0014_alter_debitomodel_aluno_alter_debitomodel_produto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="debitomodel",
            old_name="aluno",
            new_name="alunos",
        ),
        migrations.RenameField(
            model_name="debitomodel",
            old_name="produto",
            new_name="produtos",
        ),
    ]
