# Generated by Django 4.2 on 2023-12-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0016_rename_alunos_debitomodel_aluno_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debitomodel",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="debitomodel",
            name="valor",
        ),
        migrations.AddField(
            model_name="debitomodel",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=0, default=1, max_digits=5, verbose_name="Quantidade"
            ),
        ),
        migrations.AddField(
            model_name="debitomodel",
            name="valor_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Total",
            ),
        ),
        migrations.AddField(
            model_name="debitomodel",
            name="valor_unitario",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=5, verbose_name="Valor"
            ),
        ),
    ]
