# Generated by Django 4.2 on 2023-12-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadastro",
            "0017_remove_debitomodel_codigo_remove_debitomodel_valor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="debitomodel",
            name="valor_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total",
            ),
        ),
        migrations.AlterField(
            model_name="debitomodel",
            name="valor_unitario",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Valor"
            ),
        ),
    ]
