# Generated by Django 4.2 on 2023-12-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0020_alter_debitomodel_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debitomodel",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=0, default=1.0, max_digits=5, verbose_name="Quantidade"
            ),
        ),
        migrations.AlterField(
            model_name="debitomodel",
            name="valor_unitario",
            field=models.DecimalField(
                decimal_places=2, default=1.0, max_digits=10, verbose_name="Valor"
            ),
        ),
    ]
