# Generated by Django 4.2 on 2023-12-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0022_alter_debitomodel_valor_unitario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debitomodel",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=1, default=1.0, max_digits=10, verbose_name="Quantidade"
            ),
        ),
        migrations.AlterField(
            model_name="debitomodel",
            name="valor_unitario",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=10,
                verbose_name="Valor unitário",
            ),
        ),
    ]
