# Generated by Django 4.2 on 2023-12-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0033_alter_estoquemodel_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoquemodel",
            name="quantidade",
            field=models.FloatField(verbose_name="Quantidade"),
        ),
    ]
