# Generated by Django 4.2 on 2023-12-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0034_alter_estoquemodel_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoquemodel",
            name="preco_custo",
            field=models.DecimalField(
                decimal_places=5, max_digits=5, verbose_name="Preço custo"
            ),
        ),
        migrations.AlterField(
            model_name="estoquemodel",
            name="quantidade",
            field=models.IntegerField(verbose_name="Quantidade"),
        ),
        migrations.AlterField(
            model_name="estoquemodel",
            name="total_custo",
            field=models.DecimalField(
                decimal_places=5, max_digits=5, verbose_name="Total custo"
            ),
        ),
    ]
