# Generated by Django 4.2 on 2024-01-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0039_alter_estoquemodel_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrosvendamodel",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=0, max_digits=20, verbose_name="Quantidade"
            ),
        ),
        migrations.AlterField(
            model_name="cadastrosvendamodel",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Valor"
            ),
        ),
        migrations.AlterField(
            model_name="cadastrosvendamodel",
            name="valor_unitario",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Valor_unitário"
            ),
        ),
    ]
