# Generated by Django 4.2 on 2024-01-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0041_testeestoque"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TesteEstoque",
            new_name="TesteEstoqueModel",
        ),
    ]
