# Generated by Django 4.2 on 2024-01-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0042_rename_testeestoque_testeestoquemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuariosModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=25, verbose_name="Username")),
                ("password", models.CharField(max_length=25, verbose_name="Password")),
            ],
        ),
    ]
