# Generated by Django 4.2 on 2024-01-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0044_unidmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="testeestoquemodel",
            name="unidade",
            field=models.CharField(
                default="s/dados", max_length=25, null=True, verbose_name="Unidade"
            ),
        ),
    ]
