# Generated by Django 4.2 on 2024-02-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0048_alunomodel_unidade_alunomodel_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="debitomodel",
            name="unidade",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Unidade"
            ),
        ),
        migrations.AddField(
            model_name="debitomodel",
            name="usuario",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Usuário"
            ),
        ),
    ]
