# Generated by Django 4.2 on 2024-02-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0051_funcionariomodel_unidade_funcionariomodel_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicodebitomodel",
            name="criado_em",
        ),
        migrations.AddField(
            model_name="historicodebitomodel",
            name="unidade",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Unidade"
            ),
        ),
        migrations.AddField(
            model_name="historicodebitomodel",
            name="usuario",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Usuáiro"
            ),
        ),
        migrations.AlterField(
            model_name="historicodebitomodel",
            name="aluno",
            field=models.CharField(max_length=25, verbose_name="Aluno"),
        ),
        migrations.AlterField(
            model_name="historicodebitomodel",
            name="produto",
            field=models.CharField(max_length=25, verbose_name="Produto"),
        ),
    ]
