# Generated by Django 4.2 on 2024-03-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0052_remove_historicodebitomodel_criado_em_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=25, verbose_name="Ususario")),
                ("unidade", models.CharField(max_length=25, verbose_name="Unidade")),
                ("nome", models.CharField(max_length=25, verbose_name="Nome")),
            ],
        ),
    ]
