# Generated by Django 4.2 on 2024-03-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0054_clientemodel_sobrenome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientemodel",
            name="sobrenome",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Sobrenome"
            ),
        ),
    ]
