# Generated by Django 4.2 on 2024-03-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0055_alter_clientemodel_sobrenome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientemodel",
            name="sobrenome",
            field=models.CharField(
                blank=True, default="Maria", max_length=25, verbose_name="Sobrenome"
            ),
        ),
    ]
