# Generated by Django 4.2 on 2024-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0056_alter_clientemodel_sobrenome"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=25, verbose_name="Usuáiro")),
                ("unidade", models.CharField(max_length=25, verbose_name="Unidade")),
                ("nome", models.CharField(max_length=25, verbose_name="Nome")),
                ("turma", models.CharField(max_length=20, verbose_name="Turma")),
                (
                    "responsavel",
                    models.CharField(max_length=25, verbose_name="Responsavel"),
                ),
                (
                    "telefone_responsavel",
                    models.CharField(
                        max_length=25, verbose_name="Contato do responsável"
                    ),
                ),
            ],
        ),
    ]
