# Generated by Django 4.2 on 2024-03-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0057_modelaluno"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modelaluno",
            old_name="telefone_responsavel",
            new_name="tel_responsavel",
        ),
    ]
