# Generated by Django 4.2 on 2023-12-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0007_alter_alunomodel_responsavel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alunomodel",
            name="telefone_responsavel",
            field=models.CharField(
                max_length=25, verbose_name="Contato do responsável"
            ),
        ),
    ]
