# Generated by Django 4.2 on 2023-12-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0010_alter_cadastrosvendamodel_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrosvendamodel",
            name="produto",
            field=models.CharField(blank=True, max_length=25, verbose_name="Produto"),
        ),
    ]
