# Generated by Django 4.2 on 2023-12-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0031_alter_estoquemodel_preco_custo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoquemodel",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Quantidade"
            ),
        ),
    ]
