# Generated by Django 4.2 on 2023-12-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0032_alter_estoquemodel_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoquemodel",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Quantidade"
            ),
        ),
    ]
