# Generated by Django 4.2 on 2024-01-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0045_testeestoquemodel_unidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="estoquemodel",
            name="unidade",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Unidade"
            ),
        ),
        migrations.AddField(
            model_name="estoquemodel",
            name="usuario",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Usuário"
            ),
        ),
    ]
