# Generated by Django 4.2 on 2024-02-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0049_debitomodel_unidade_debitomodel_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastrosvendamodel",
            name="unidade",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Unidade"
            ),
        ),
        migrations.AddField(
            model_name="cadastrosvendamodel",
            name="usuario",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Usuário"
            ),
        ),
    ]
